### ISSUE TITLE
sidenotes not rendered in mobile browser(s?)

### ISSUE THREAD

**Issue by Turnsole** [clayh53/tufte-jekyll#3]
In Chrome for Android at least, the sidenotes never appear.

**Comment by clayh53** [comment]
I don't have access to any Android devices, so troubleshooting this is difficult.

**Comment by Turnsole** [comment]
I'll see if I can figure it out, then. You could use an emulator, but that's a fair amount to ask of you if mobile isn't one of your priorities.

**Comment by clayh53** [comment]
I did this sort of on a lark, and it works fine on iOS devices. I suspect there is a breakpoint issue in the CSS

**Comment by Joshfindit** [comment]
Came here because it's both impressive and flawed on an iPhone 4.
The impressive part: On portrait-orientation load, the main content is sized properly on screen, along with  images. It's simple to zoom out and see the space where the sidenotes would be.

The flawed part: when zooming out, the margin notes are not shown.
Flipping to landscape, the margin notes are shown, but now the content + margin notes are 50% of the width of the page, with another margin being blank.

This is a fun project, and the only part that seems like a bug is that the margin notes don't show on portrait.

**Comment by clayh53** [comment]
The sidenote in mobile issue has now been fixed
