### ISSUE TITLE
Content in the margin should use <aside>

### ISSUE THREAD

**Issue by reitzig** [clayh53/tufte-jekyll#32]
In the spirit of semantic HTML, content put in the margin should be wrapped in `<aside>` tags.

(That can also be useful when filtering excerpts: simply hide all `aside` nodes.)

The way the plugins currently work, though, they create span-level nodes. `<aside>` is a block tag and illegal to use in the same way, i.e. within `<p>` tags. Kramdown will actually escape the tag.

So a larger redesign is necessary; I don't have a proposal right now.

**Comment by xHN35RQ** [comment]
Actually this is a design decision made by [tufte-css](
https://github.com/edwardtufte/tufte-css) developers, see the following 2 issues for this:

https://github.com/edwardtufte/tufte-css/issues/24
https://github.com/edwardtufte/tufte-css/issues/40

If tufte-css moves to `<aside>` then so should tufte-jekyll. Until then there really isn't an issue since tufte-jekyll strives to match tufte-css as much as possible.

**Comment by clayh53** [comment]
I'm with Nick on this one. I think it is best to keep this jekyll theme in sync with the tufte.css as much as possible. And the sidenotes and marginnotes also behave semantically like footnotes as well. I am not sure that the HTML guidelines are for footnotes.

**Comment by clayh53** [comment]
Thinking about this, I decided to try and add some <aside> wrappers around margin content. Turns out that the Ruby code just sort of barfs on that and it writes a literal "<aside>" into the HTML. I am not enough of a Rubyhead to understand what exactly is going on here, but I welcome any thoughts on this. For now, I will leave it semantically unstyled.
