### ISSUE TITLE
Add epigraph css to tufte jekyll ?

### ISSUE THREAD

**Issue by reyman** [clayh53/tufte-jekyll#61]
Hi,

Do you think it's possible to push the **tufte epigraph css** behavior ( https://edwardtufte.github.io/tufte-css/) into tufte jekyll ? 

Thanks 
SR

**Comment by clayh53** [comment]
Yes, that looks very doable. It appears that they have made some recent updates to the Tufte-CSS repo and I would like to keep this theme with feature-parity with the CSS source repo. My main goal with the Jekyll theme is to make it even easier to write blogs in this style by encapsulating these features in Jekyll-style Liquid tags instead of slogging through a bunch of HTML. 

One other thing I have been toying with is having Sparklines functionality from a Jekyll/Liquid tag. My thought is you could feed the tag either data directly or use a json feed that would synchronize automagically.  Any thoughts about that?

**Comment by clayh53** [comment]
I have added an epigraph tag set to the repository
